#!/bin/bash

MAX_CONN=100
LOG_FILE="/var/log/ddos_block.log"

ip_list=$(ss -ntu | awk '{print $5}' | cut -d: -f1 | sort | uniq -c | sort -nr)

echo "$ip_list" | while read count ip; do
    if [[ $count -gt $MAX_CONN && $ip =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
        already_blocked=$(iptables -L INPUT -v -n | grep "$ip")
        
        if [ -z "$already_blocked" ]; then
            iptables -A INPUT -s "$ip" -j DROP
            echo "$(date): Blocked $ip with $count connections" >> $LOG_FILE
            # curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"DDoS 공격 감지: $ip 차단 완료\"}" https://hooks.slack.com/services/...
        fi
    fi
done
